### ISSUE TITLE
help: Technical Issue Encountered while Replicating PatchTST using tsfm

### ISSUE THREAD

**Issue by edwardhuanghz** [ibm-granite/granite-tsfm#38] opened 2024-04-10 06:50 UTC
HI,  i run  a example code to Replicating PatchTST using tsfm(see script [demo-code2.txt](https://github.com/IBM/tsfm/files/14928405/demo-code2.txt))

cmd: df.item_id.unique()
output: array(['000858', '002304', '600519', '600809'], dtype=object)
<img width="843" alt="image" src="https://github.com/IBM/tsfm/assets/43718840/a0e1be2c-6e48-4073-b1d5-24bb366aa9c2">

Q1:  "item_id" return not correctly, expect return the same as df.item_id.unique() returns
<img width="816" alt="image" src="https://github.com/IBM/tsfm/assets/43718840/64d258fd-954a-496f-9a50-b4e62e6e6d06">

Q2: feature_extractor define,run bug
<img width="961" alt="image" src="https://github.com/IBM/tsfm/assets/43718840/970885a9-5208-461e-91e3-4eb0a5a3fb38">
<img width="910" alt="image" src="https://github.com/IBM/tsfm/assets/43718840/33a7ee43-a03d-4974-8771-3fe2f07d6cd4">

Q3:  how to predict (future 3 year)  4*3= 12 period, eg.2023-12-31  ~2027-09-30,plz give a example, and inverse  scale targets to normal data 

ths

see below:
1. source data 
[data.csv](https://github.com/IBM/tsfm/files/14928341/data.csv)
2. script(python)
[demo-code2.txt](https://github.com/IBM/tsfm/files/14928405/demo-code2.txt)

**Comment by wgifford** [comment] 2024-04-11 01:35
Thank you @edwardhuanghz . I was able to reproduce the issue and I have created a PR for a fix. Please try the new branch and confirm that the issue is resolved.

Thanks!

**Comment by edwardhuanghz** [comment] 2024-04-14 06:37
> Thank you @edwardhuanghz . I was able to reproduce the issue and I have created a PR for a fix. Please try the new branch and confirm that the issue is resolved.
> 
> Thanks!

fixed ok now? ,does not work, plz check,ths

**Comment by edwardhuanghz** [comment] 2024-04-22 08:04
<img width="927" alt="image" src="https://github.com/IBM/tsfm/assets/43718840/e4a4fe1d-e9b2-4ee4-a2a1-32079a91dbab">

**Comment by wgifford** [comment] 2024-04-23 15:27
On the branch `issue_38`, this is what I see:

<img width="1008" alt="image" src="https://github.com/IBM/tsfm/assets/79663411/d60f0610-add8-4e09-ad26-1b807ca42e15">

Please install from that branch, and try your code.

**Comment by wgifford** [comment] 2024-04-25 18:01
@edwardhuanghz I merged the `issue_38` branch to main.

**Comment by wgifford** [comment] 2024-05-13 20:09
Closing, as I believe this is resolved -- please reopen if you are still having issues.

**Closed by wgifford** 2024-05-13 20:09 UTC
